name: vpn_sound
description: VPN sound notifier
publish_to: none
version: 1.0.0+4
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.0
  audioplayers: ^6.0.0
  flutter_foreground_task: ^8.0.0
flutter:
  uses-material-design: true
